### ISSUE TITLE
Lesson linking to incorrect notebook?

### ISSUE THREAD

**Issue by Davidkeebler** [learn-co-curriculum/dsc-tuning-neural-networks-with-normalization-lab-v2-1#2]
## Link to Canvas

https://learning.flatironschool.com/courses/6486/assignments/243757?module_item_id=573828

## Issue Subtype

- [ ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [x ] Layout/rendering issue
- [ ] Instructions unclear
- [x ] Other (explain below)

### Source

```

```

### Concern

This lesson links to a notebook called "data_preprocessing" which performs basic data cleaning and preparation for machine learning without any explanation and without training a neural network. This is not what is described in the lesson page.

## What OS Are You Using?

- [ ] OS X
- [ ] Windows
- [ ] WSL
- [ ] Linux
- [ ] Saturn Cloud from Canvas

**Comment by bpurdy-ds** [comment]
Fixed. Thank you for pointing this out.
