### ISSUE TITLE
The code that includes sparse_output=False when handling categorical variables is bringing an error. Can this be changed to something else?

### ISSUE THREAD

**Issue by JoanWambua** [learn-co-curriculum/dsc-tuning-neural-networks-with-normalization-lab-v2-1#3]
## Issue Subtype

- [x] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [ ] Other (explain below)

### Source

```

```

## What OS Are You Using?

- [ ] OS X
- [x] Windows
- [ ] WSL
- [ ] Linux
- [ ] Saturn Cloud from Canvas

**Comment by bpurdy-ds** [comment]
Hello. Thank you for bringing this to our attention. We'll take a look.

**Comment by bpurdy-ds** [comment]
I ran the solution branch code locally and it is working for me. Further, I'm not seeing the line of code being referred to above (sparse_output=False). I am going to close the ticket. I'd reach out to your instructor if you are still having troubles. If your instructor isn't able to help you, then please reopen this issue.
